### PR TITLE
Add Docker

### PR DESCRIPTION
**Pull request by AdrienLoupforest**

### CODE REVIEW

**Comment by TheGoodwin** [comment]
I don't see how a docker image adds much to the bot. Can you explain more?

**Comment by AdrienLoupforest** [comment]
With docker you can develop on every computer with docker and docker-compose and you can deploy easily on a raspberry for example.

**Review by ShiiFu — COMMENTED** [review]
I think that docker is a real added value.

Why don't include README-DOCKER as a part of the main README?

**Comment by TheGoodwin** [comment]
I'm not an expert on Docker...
Does this image includes npm, nvm and nodejs ?

**Comment by AdrienLoupforest** [comment]
I didn't wanted to add it at the end of the REAMDE because soon or later we will have an unlimited README which is not understandable. But we can include the README-DOCKER as a part of the main README until we have more things to add in it.

**Comment by AdrienLoupforest** [comment]
This image include npm and node Boron which is LTS.

**Comment by TheGoodwin** [comment]
Ok, can you add the README-DOCKER at the end of the README before any merging ?

**Comment by AdrienLoupforest** [comment]
Ok i will do this.

**Comment by TheGoodwin** [comment]
Seems good so far.

**Pull request merged**
